#pragma once
#include <string>
using std::string;

// Pokemon Define names
#define	BULBASAUR	0
#define	IVYSAUR		1
#define	VENUSAUR	2
#define	CHARMANDER	3
#define	CHARMELEON	4
#define	CHARIZARD	5
#define	SQUIRTLE	6
#define	WARTORTLE	7
#define	BLASTOISE	8
#define	PIDGEY		9
#define	PIDGEOTTO	10
#define	PIDGEOT		11
#define	RATTATA		12
#define	RATICATE	13
#define	SPEAROW		14
#define	FEAROW		15
#define	PIKACHU		16
#define	RAICHU		17
#define	VULPIX		18
#define	NINETAILS	19
#define	ODDISH		20
#define	GLOOM		21
#define	VILEPLUME	22
#define	PARAS		23
#define	PARASECT	24
#define	MEOWTH		25
#define	PERSIAN		26
#define	PSYDUCK		27
#define	GOLDUCK		28
#define	GROWLITHE	29
#define	ARCANINE	30
#define	POLIWAG		31
#define	POLIWHIRL	32
#define	POLIWRATH	33
#define	BELLSPROUT	34
#define	WEEPINBELL	35
#define	VICTREEBELL	36
#define	TENTACOOL	37
#define	TENTACRUEL	38
#define	GEODUDE		39
#define	GRAVLER		40
#define	GOLEM		41
#define	PONYTA		42
#define	RAPIDASH	43
#define	SLOWPOKE	44
#define	SLOWBRO		45
#define	MAGNEMITE	46
#define	MAGNETON	47
#define	DODUO		48
#define	DODRIO		49
#define	SEEL		50
#define	DEWGONG		51
#define	SHELLDER	52
#define	CLOYSTER	53
#define	ONIX		54
#define	KRABBY		55
#define	KINGLER		56
#define	EXEGGCUTE	57
#define	EXEGGUTOR	58
#define	CUBONE		59
#define	MAROWAK		60
#define	RYHORN		61
#define	RHYDON		62
#define	TANGELA		63
#define	HORSEA		64
#define	SEADRA		65
#define	GOLDEEN		66
#define	SEAKING		67
#define	STARYU		68
#define	STARMIE		69
#define	ELECTRABUZZ	70
#define	MAGMAR		71
#define	MAGIKARP	72
#define	GYRADOS		73
#define	LAPRAS		74
#define	DITTO		75
#define	EEVEE		76
#define	VAPOREON	77
#define	JOLTEON		78
#define	FLAREON		79
#define	OMANYTE		80
#define	OMASTAR		81
#define	KABUTO		82
#define	KABUTOPS	83
#define	SNORLAX		84

// Pokemon Types
#define	NORMAL		1
#define	WATER		2
#define GRASS		3
#define	GROUND		4
#define	FIRE		5
#define	ELECTRIC	6

// Pokemon string names
struct {
	string names[85] = {
		"BULBASAUR", "IVYSAUR", "VENUSAUR", "CHARMANDER", "CHARMELEON",
		"CHARIZARD", "SQUIRTLE", "WARTORTLE", "BLASTOISE", "PIDGEY",
		"PIDGEOTTO", "PIDGEOT", "RATTATA", "RATICATE", "SPEAROW",
		"FEAROW", "PIKACHU", "RAICHU", "VULPIX", "NINETAILS",
		"ODDISH", "GLOOM", "VILEPLUME", "PARAS", "PARASECT",
		"MEOWTH", "PERSIAN", "PSYDUCK", "GOLDUCK", "GROWLITHE",
		"ARCANINE", "POLIWAG", "POLIWHIRL", "POLIWRATH", "BELLSPROUT",
		"WEEPINBELL", "VICTREEBELL", "TENTACOOL", "TENTACRUEL", "GEODUDE",
		"GRAVLER", "GOLEM", "PONYTA", "RAPIDASH", "SLOWPOKE",
		"SLOWBRO", "MAGNEMITE", "MAGNETON", "DODUO", "DODRIO",
		"SEEL", "DEWGONG", "SHELLDER", "CLOYSTER", "ONIX",
		"KRABBY", "KINGLER", "EXEGGCUTE", "EXEGGUTOR", "CUBONE",
		"MAROWAK", "RYHORN", "RHYDON", "TANGELA", "HORSEA",
		"SEADRA", "GOLDEEN", "SEAKING", "STARYU", "STARMIE",
		"ELECTRABUZZ", "MAGMAR", "MAGIKARP", "GYRADOS", "LAPRAS",
		"DITTO", "EEVEE", "VAPOREON", "JOLTEON", "FLAREON",
		"OMANYTE", "OMASTAR", "KABUTO", "KABUTOPS", "SNORLAX"
	};
	
	int poke_type[85] = { GRASS, GRASS, GRASS, FIRE, FIRE,
		FIRE, WATER, WATER, WATER, NORMAL,
		NORMAL, NORMAL, NORMAL, NORMAL, NORMAL,
		NORMAL, ELECTRIC, ELECTRIC, FIRE, FIRE,
		GRASS, GRASS, GRASS, GRASS, GRASS,
		NORMAL, NORMAL, WATER, WATER, FIRE,
		FIRE, WATER, WATER, WATER, GRASS,
		GRASS, GRASS, WATER, WATER, GROUND,
		GROUND, GROUND, FIRE, FIRE, WATER,
		WATER, ELECTRIC, ELECTRIC, NORMAL, NORMAL,
		WATER, WATER, WATER, WATER, GROUND,
		WATER, WATER, GRASS, GRASS, GROUND,
		GROUND, GROUND, GROUND, GRASS, WATER,
		WATER, WATER, WATER, WATER, WATER,
		ELECTRIC, FIRE, WATER, WATER, WATER,
		NORMAL, NORMAL, WATER, ELECTRIC, FIRE,
		WATER, WATER, WATER, WATER, NORMAL
	};
	string move_names[14] = {
		"HYDRO PUMP", "BUBBLE BEAM", "FLAMETHROWER", "FIRE SPIN", "RAZOR LEAF", "VINE WHIP", "EARTHQUAKE", 
		"DIG", "THUNDER PUNCH", "THUNDERBOLT", "QUICK ATTACK", "TACKLE", "MEGA KICK", "FURY ATTACK"
	};
	int move_damage[14] = { 30, 40, 30, 30, 40, 30, 40, 30, 40, 20, 20, 30, 30 };	// Damage per move
	int move_pp[14] = { 20, 30, 20, 30, 20, 30, 20, 30, 20, 30, 10, 10, 15, 15 };	// PP cost per move
	int move_type[14] = { WATER, WATER, FIRE, FIRE, GRASS, GRASS, GROUND, GROUND, ELECTRIC, ELECTRIC, NORMAL, NORMAL, NORMAL, NORMAL};
} poke_data; 
